const api=window.bigbrainDesktop;let step=1;let form={ownerName:'',ownerEmail:'',name:'My Brain',mode:'local',apiKey:'',existingHome:''};let state;
const content=document.querySelector('#step-content');const steps=[...document.querySelectorAll('.step')];
function render(){steps.forEach((el,i)=>{el.classList.toggle('active',i===step-1);el.classList.toggle('done',i<step-1)});const pages={
1:`<h1>Welcome to BigBrain</h1><p>First, tell your local brain who you are. Your email stays on this Mac.</p>${field('ownerName','Your name','Your name')}${field('ownerEmail','Email','you@example.com','email')}${actions(false)}`,
2:`<h1>Choose your brain</h1><p>Create a new brain, or connect one that already exists without moving its files.</p>${form.existingHome?`<div class="existing-box"><strong>${escapeHtml(form.name)}</strong><small>${escapeHtml(form.existingHome)}</small></div><p><button class="secondary" id="clear-existing">Create a new brain instead</button></p>`:`${field('name','New brain name','My Brain')}<p><button class="secondary" id="choose-existing">Use an existing brain…</button></p>`}${actions(true)}`,
3:`<h1>Choose a mode</h1><p>BigBrain keeps your files and index isolated from every other brain.</p><div class="choice"><strong>Local</strong> <span class="badge">Recommended</span><p>Stored privately on this Mac. Hosted mode is coming later.</p></div>${actions(true)}`,
4:`<h1>Connect AI</h1><p>Use your own OpenAI API key. It is validated once and stored securely in macOS Keychain—not in your brain or logs.</p>${field('apiKey','OpenAI API key','sk-…','password')}<div id="error"></div>${actions(true,form.existingHome?'Connect brain':'Create brain')}`};content.innerHTML=pages[step];content.querySelectorAll('input').forEach(el=>{el.value=form[el.name]||'';el.oninput=()=>form[el.name]=el.value});content.querySelector('[data-next]')?.addEventListener('click',next);content.querySelector('[data-back]')?.addEventListener('click',()=>{step--;render()});content.querySelector('#choose-existing')?.addEventListener('click',chooseExisting);content.querySelector('#clear-existing')?.addEventListener('click',()=>{form.existingHome='';form.name='My Brain';render()})}
async function chooseExisting(){try{const existing=await api.chooseExistingBrain();if(!existing)return;form.existingHome=existing.home;form.name=existing.name;render()}catch(e){content.insertAdjacentHTML('beforeend',`<div class="error">${escapeHtml(e.message)}</div>`)}}
function field(name,label,placeholder,type='text'){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" placeholder="${placeholder}" autocomplete="off"></div>`}function actions(back,label='Continue'){return `<div class="actions">${back?'<button class="secondary" data-back>Back</button>':'<span></span>'}<button class="primary" data-next>${label}</button></div>`}
async function next(){if(step<4){step++;render();return}const btn=content.querySelector('[data-next]');btn.disabled=true;btn.textContent='Creating and checking your brain…';try{const result=await api.createBrain(form);showConnection(result)}catch(e){content.querySelector('#error').innerHTML=`<div class="error">${escapeHtml(e.message)}</div>`;btn.disabled=false;btn.textContent='Create brain'}}
function showConnection(result){step=5;steps.forEach((el,i)=>{el.classList.toggle('active',i===4);el.classList.toggle('done',i<4)});content.innerHTML=`<h1>Your brain is ready</h1><p>Connect any MCP-compatible agent using this endpoint.</p><div class="copybox" id="copy">${escapeHtml(result.instructions.generic)}</div><p><button class="secondary" id="copybtn">Copy instructions</button></p><details><summary>Codex</summary><div class="copybox">${escapeHtml(result.instructions.codex)}</div></details><details><summary>Claude</summary><div class="copybox">${escapeHtml(result.instructions.claude)}</div></details><div class="warning"><strong>Back up your brain.</strong> Everything could be lost if you delete its folder or lose access to this device. Private GitHub backup is coming soon.</div><div class="actions"><span></span><button class="primary" id="open">Open BigBrain</button></div>`;document.querySelector('#copybtn').onclick=()=>navigator.clipboard.writeText(result.instructions.generic);document.querySelector('#open').onclick=loadApp}
async function loadApp(){state=await api.state();document.querySelector('#onboarding').classList.add('hidden');document.querySelector('#app').classList.remove('hidden');renderTabs()}
function renderTabs(){const tabs=document.querySelector('#tabs');tabs.innerHTML=state.brains.map(b=>`<button class="tab ${b.id===state.activeBrainId?'active':''}" data-id="${b.id}">${escapeHtml(b.name)} · ${b.status}</button>`).join('')+'<button class="tab add" id="add">＋ New brain</button>';tabs.querySelectorAll('[data-id]').forEach(el=>el.onclick=async()=>{await api.activate(el.dataset.id);state.activeBrainId=el.dataset.id;renderTabs()});tabs.querySelector('#add').onclick=()=>{document.querySelector('#app').classList.add('hidden');document.querySelector('#onboarding').classList.remove('hidden');step=1;form={ownerName:'',ownerEmail:'',name:'My Brain',mode:'local',apiKey:'',existingHome:''};render()};const brain=state.brains.find(b=>b.id===state.activeBrainId);document.querySelector('#content').innerHTML=brain?`<iframe src="${brain.dashboardUrl}"></iframe>`:'<div class="empty">Create your first brain.</div>'}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
(async()=>{state=await api.state();if(state.brains.some(b=>b.onboarding?.completed))loadApp();else render()})().catch(e=>{content.innerHTML=`<div class="error">${escapeHtml(e.message)}</div>`});
