const api=window.bigbrainDesktop;let step=1;let form={ownerName:'',ownerEmail:'',name:'My Brain',mode:'',apiKey:'',existingHome:'',serviceUrl:''};let state;
const content=document.querySelector('#step-content');const steps=[...document.querySelectorAll('.step')];
function render(){steps.forEach((el,i)=>{el.classList.toggle('active',i===step-1);el.classList.toggle('done',i<step-1)});const localPages={
2:`<h1>Who will use this brain?</h1><p>Your identity stays on this Mac and helps BigBrain recognize your work.</p>${field('ownerName','Your name','Your name')}${field('ownerEmail','Email','you@example.com','email')}${actions(true)}`,
3:`<h1>Set up your brain</h1><p>Create a new brain on this device, or use an existing brain folder without moving its files.</p>${form.existingHome?`<div class="existing-box"><strong>${escapeHtml(form.name)}</strong><small>${escapeHtml(form.existingHome)}</small></div><p><button class="secondary" id="clear-existing">Create a new brain instead</button></p>`:`${field('name','New brain name','My Brain')}<p><button class="secondary" id="choose-existing">Use an existing brain folder…</button></p>`}${actions(true)}`,
4:`<h1>Connect AI</h1><p>Use your own OpenAI API key. It is validated once and stored securely in macOS Keychain—not in your brain or logs.</p>${field('apiKey','OpenAI API key','sk-…','password')}<div id="error"></div>${actions(true,'Run BigBrain')}`};const servicePages={
2:`<h1>Connect to an existing BigBrain</h1><p>Enter the address of BigBrain already running on this machine, your organization’s network, or online.</p>${field('serviceUrl','BigBrain service address','https://brain.example.com','url')}${actions(true)}`,
3:`<h1>Check the connection</h1><p>The desktop app will verify the BigBrain service and save this connection on this Mac.</p><div class="existing-box"><strong>BigBrain service</strong><small>${escapeHtml(form.serviceUrl||'Enter a service address in the previous step.')}</small></div>${actions(true)}`,
4:`<h1>Ready to connect</h1><p>If this BigBrain requires sign-in, you’ll be asked to sign in when its dashboard opens.</p><div id="error"></div>${actions(true,'Connect BigBrain')}`};const pages={
1:`<h1>Give your AI persistent memory</h1><p>Choose where BigBrain runs. You can change between connected brains later.</p><button class="choice choice-option" data-mode="local"><strong>Run BigBrain on this device</strong><p>Set up and manage a brain directly on this Mac.</p></button><button class="choice choice-option" data-mode="service"><strong>Connect to an existing BigBrain</strong><p>Use BigBrain already running here, on your organization’s network, or online.</p></button>`,...(form.mode==='service'?servicePages:localPages)};content.innerHTML=pages[step];content.querySelectorAll('input').forEach(el=>{el.value=form[el.name]||'';el.oninput=()=>form[el.name]=el.value});content.querySelectorAll('[data-mode]').forEach(el=>el.addEventListener('click',()=>{form.mode=el.dataset.mode;step=2;render()}));content.querySelector('[data-next]')?.addEventListener('click',next);content.querySelector('[data-back]')?.addEventListener('click',()=>{step--;render()});content.querySelector('#choose-existing')?.addEventListener('click',chooseExisting);content.querySelector('#clear-existing')?.addEventListener('click',()=>{form.existingHome='';form.name='My Brain';render()})}
async function chooseExisting(){try{const existing=await api.chooseExistingBrain();if(!existing)return;form.existingHome=existing.home;form.name=existing.name;render()}catch(e){content.insertAdjacentHTML('beforeend',`<div class="error">${escapeHtml(e.message)}</div>`)}}
function field(name,label,placeholder,type='text'){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" placeholder="${placeholder}" autocomplete="off"></div>`}function actions(back,label='Continue'){return `<div class="actions">${back?'<button class="secondary" data-back>Back</button>':'<span></span>'}<button class="primary" data-next>${label}</button></div>`}
async function next(){if(step<4){step++;render();return}const btn=content.querySelector('[data-next]');btn.disabled=true;const service=form.mode==='service';btn.textContent=service?'Checking and connecting…':'Creating and checking your brain…';try{if(service){await api.connectService({serviceUrl:form.serviceUrl});showServiceConnection()}else{const result=await api.createBrain(form);showConnection(result)}}catch(e){content.querySelector('#error').innerHTML=`<div class="error">${escapeHtml(e.message)}</div>`;btn.disabled=false;btn.textContent=service?'Connect BigBrain':'Run BigBrain'}}
function showServiceConnection(){step=5;steps.forEach((el,i)=>{el.classList.toggle('active',i===4);el.classList.toggle('done',i<4)});content.innerHTML=`<h1>BigBrain connected</h1><p>This connection is saved on this Mac. Open BigBrain to use its dashboard.</p><div class="actions"><span></span><button class="primary" id="open">Open BigBrain</button></div>`;document.querySelector('#open').onclick=loadApp}
function showConnection(result){step=5;steps.forEach((el,i)=>{el.classList.toggle('active',i===4);el.classList.toggle('done',i<4)});content.innerHTML=`<h1>Your brain is ready</h1><p>Connect any MCP-compatible agent using this endpoint.</p><div class="copybox" id="copy">${escapeHtml(result.instructions.generic)}</div><p><button class="secondary" id="copybtn">Copy instructions</button></p><details><summary>Codex</summary><div class="copybox">${escapeHtml(result.instructions.codex)}</div></details><details><summary>Claude</summary><div class="copybox">${escapeHtml(result.instructions.claude)}</div></details><div class="warning"><strong>Back up your brain.</strong> Everything could be lost if you delete its folder or lose access to this device. Private GitHub backup is coming soon.</div><div class="actions"><span></span><button class="primary" id="open">Open BigBrain</button></div>`;document.querySelector('#copybtn').onclick=()=>navigator.clipboard.writeText(result.instructions.generic);document.querySelector('#open').onclick=loadApp}
async function loadApp(skipActive=false){state=await api.state();document.querySelector('#onboarding').classList.add('hidden');document.querySelector('#app').classList.remove('hidden');renderBrainSelector();if(skipActive)document.querySelector('#content').innerHTML='<div class="empty">Choose a brain, or add another one.</div>';else showActiveBrain()}
function renderBrainSelector(){const tabs=document.querySelector('#tabs');const active=state.brains.find(b=>b.id===state.activeBrainId);tabs.innerHTML=`<div class="brain-select-wrap"><button class="brain-trigger" id="brain-trigger" type="button" aria-haspopup="menu" aria-expanded="false"><span>${escapeHtml(active?.name||'Choose brain')}</span><span class="select-chevron" aria-hidden="true"></span></button><div class="brain-menu hidden" id="brain-menu" role="menu">${state.brains.map(b=>`<button type="button" role="menuitemradio" aria-checked="${b.id===state.activeBrainId}" data-brain-id="${escapeHtml(b.id)}"><span>${escapeHtml(b.name)}</span><span class="menu-check">${b.id===state.activeBrainId?'✓':''}</span></button>`).join('')}<div class="menu-separator"></div><button type="button" role="menuitem" data-new-brain><span>＋ Add brain…</span></button></div></div>`;const trigger=tabs.querySelector('#brain-trigger');const menu=tabs.querySelector('#brain-menu');const close=()=>{menu.classList.add('hidden');trigger.setAttribute('aria-expanded','false')};trigger.onclick=()=>{const opening=menu.classList.contains('hidden');menu.classList.toggle('hidden');trigger.setAttribute('aria-expanded',String(opening));if(opening)menu.querySelector('button')?.focus()};menu.querySelectorAll('[data-brain-id]').forEach(item=>item.onclick=async()=>{const id=item.dataset.brainId;close();await api.activate(id);state.activeBrainId=id;renderBrainSelector();showActiveBrain()});menu.querySelector('[data-new-brain]').onclick=()=>{close();startOnboarding()};menu.onkeydown=event=>{const items=[...menu.querySelectorAll('button')];const index=items.indexOf(document.activeElement);if(event.key==='Escape'){close();trigger.focus()}else if(event.key==='ArrowDown'){event.preventDefault();items[(index+1)%items.length]?.focus()}else if(event.key==='ArrowUp'){event.preventDefault();items[(index-1+items.length)%items.length]?.focus()}};setTimeout(()=>document.addEventListener('pointerdown',event=>{if(!tabs.contains(event.target))close()},{once:true}),0)}
function startOnboarding(){document.querySelector('#app').classList.add('hidden');document.querySelector('#onboarding').classList.remove('hidden');step=1;form={ownerName:'',ownerEmail:'',name:'My Brain',mode:'',apiKey:'',existingHome:'',serviceUrl:''};render()}
function showActiveBrain(){const brain=state.brains.find(b=>b.id===state.activeBrainId);const region=document.querySelector('#content');if(!brain){region.innerHTML='<div class="empty">Run BigBrain here or connect to an existing BigBrain.</div>';return}if(brain.connectionType==='service'){region.innerHTML='<div class="empty">Opening BigBrain…</div>';void api.openBrain(brain.id);return}const current=region.querySelector('iframe');if(current?.dataset.brainId===brain.id)return;document.querySelector('#tabs').classList.add('dashboard-loading');region.innerHTML=`<iframe data-brain-id="${escapeHtml(brain.id)}" src="${escapeHtml(brain.dashboardUrl)}"></iframe>`}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
(window=>window.addEventListener('message',event=>{const frame=document.querySelector('#content iframe');if(event.source!==frame?.contentWindow||event.data?.type!=='bigbrain-dashboard-status')return;document.querySelector('#tabs').classList.toggle('dashboard-loading',event.data.status!=='ready')}))(window);
(async()=>{state=await api.state();if(state.brains.some(b=>b.onboarding?.completed))loadApp(new URLSearchParams(location.search).has('select'));else render()})().catch(e=>{content.innerHTML=`<div class="error">${escapeHtml(e.message)}</div>`});
